### ISSUE TITLE
Checker Skull Cube

### ISSUE THREAD

**Issue by The-Queen55142** [ENDERZOMBI102/Decoration-Station#11]
This happens with both the red and blue versions. I'm not sure what this is, but the grey areas seem to be highly reflective. (Going pink when i turned the light to the left Pink and put the cube near it)

https://steamcommunity.com/sharedfiles/filedetails/?id=2025981171

**Comment by The-Queen55142** [comment]
Edited cause wrong image copied lol

**Comment by Flash4433** [comment]
This is known, it's most likely using the wrong material type. I'll have to check out the .qc file.

**Comment by Flash4433** [comment]
Oh wait, that's another thing. It seems it's missing some sort of texture, I probably forgot to add it or something...

**Comment by Flash4433** [comment]
That should be fixed now, I was pointing to the wrong path. I wish to further upgrade the skull cube so its reflections are the same as a normal P1 cube. I've done everything I can in the .vmt, so perhaps this needs some work on the model itself or the textures.
