### ISSUE TITLE
Skull Pedestal Button Floating Bug

### ISSUE THREAD

**Issue by King0191** [ENDERZOMBI102/Decoration-Station#4]
It likes to float a bit off the ground

![image](https://user-images.githubusercontent.com/37309250/75791476-9d7e2e00-5d3a-11ea-8952-6baa64d320bd.png)

**Comment by Flash4433** [comment]
This is a leftover from the instance itself. It's supposed to add a small slab in P1 style. I removed this while there isn't a Clean version. I'll finish the Clean version later, and add the slab in P1. I'll probably make a custom model later on for Clean.

**Comment by Flash4433** [comment]
Also, check out the skull-cube branch. It has an alternate version with blue stripes. You can choose between blue or red stripes in the item menu. Just right click the item, and check the drop-down menu on the bottom-left corner of the window that appears.

**Comment by King0191** [comment]
The override didn't want to work (gave me a "No alternate versions" text) So I edited the code slightly to separate them into two items for the time being. (removed the "override" and the brackets corresponding with the override and changed the name of the red version) , Very cool tho!

**Comment by Flash4433** [comment]
That's weird, it's working for me... Gotta check if I did something wrong

**Comment by Flash4433** [comment]
Both of these issues have been fixed. I added a Clean Version that has its coordinates fixed, and the P1 Version now has the slab, as other pedestals do. I also fixed the Alternate Version, I apparently deleted the change or something :P
