### ISSUE TITLE
Custom Start

### ISSUE THREAD

**Issue by Danimob** [ENDERZOMBI102/Decoration-Station#7]
An opposite of the trigger end thing (thx for doing that btw.).  Where it is placed the player starts the map, instead of in the entrance section.  This would be good for making seamless transitions between chambers.  Sort of like the info_player_start entity in hammer (I think that is what it is called.)

**Comment by Flash4433** [comment]
Well, apparently there is no need for the trigger. The user saismee#1231 has made a custom start, in the name of Player Spawn. Here's the link https://github.com/CheezyPig/saismee-addons/releases/latest
